- lib/convert/src/impls/cloud/version/mod.rs
- svc/api/cloud/default-site/index.html
- svc/api/identity/src/route/events.rs
Make user event decoding infallible in api-identity
> Make user event decoding infallible in api-identity

- lib/bolt/cli/src/commands/output.rs
- svc/api/identity/Service.toml
- Add `bolt output service-databases` command to view all recursive database dependencies
- Fix api-identity database dependencies
> Add missing database to api-identity, new bolt command

- docs/infrastructure/k3s/TROUBLESHOOTING.md
- svc/api/auth/src/utils.rs
Reverts changes to `SameSite` on hub cookies to use `None`. This is because the hub is on a different domain than the API endpoints.
> Revert SameSite cookie to None

- .github/actions/pre-init/action.yaml
- .github/workflows/bolt-check.yaml
- .github/workflows/bolt-test.yaml
- lib/bolt/config/src/ns.rs
- lib/bolt/core/src/dep/cargo/cli.rs
Docker builds take a long time to build. sccache has already sped up CI significantly by making bolt check run faster. Adding sccache to Docker builds cuts ~50% off the build time.
Fixes SVC-3427
Depends on #194
> Configurable sccache for service Docker builds

- errors/api/bad-cookie.md
- errors/api/missing-cookie.md
- lib/api-helper/build/src/macro_util.rs
- lib/api-helper/macros/src/lib.rs
- svc/Cargo.lock
- svc/api/auth/Cargo.toml
- svc/api/auth/src/route/identity.rs
- svc/api/auth/src/route/mod.rs
- svc/api/auth/src/route/tokens.rs
Currenlty, Rivet parses the first cookie with the given key in the auth request. However, there are frequently situations (either localhost changing origins or having the wrong `Domain`) where there are residual cookies created by a different cluster.
This PR makes it so it parses all the cookies and finds the first one that can be parsed (i.e. has the correct JWT key). This way, the correct cookie is always parsed.
> Gracefully ignore cookies that can't be decoded

- svc/api/matchmaker/src/route/lobbies.rs
- svc/pkg/mm/types/msg/lobby-find.proto
- svc/pkg/mm/worker/src/workers/lobby_find/mod.rs
- svc/pkg/mm/worker/src/workers/player_remove.rs
- svc/pkg/mm/worker/tests/lobby_find.rs
- svc/pkg/mm/worker/tests/player_remove.rs
mm-lobby-find creates players premptively in Redis before inserting in to Cockroach. If the Cockroach insertion fails, then the players are not able to be removed from Redis.
Now we can fallback to reading the plyaer's state from Redis to remove the player if the player does not exist in Cockroach.
> Redis fallback in mm-player-remove

- svc/pkg/monolith/standalone/worker/src/lib.rs
- svc/pkg/monolith/standalone/worker/src/main.rs
This closes #211.
As mentioned in the issue, the duplicated code is in the main and lib files. I opted to remove the code from lib and keep the one in main, since that seems to be what most other services do.
> Remove duplicated code in monolith-worker

- lib/chirp/worker/src/macros.rs
- svc/pkg/analytics/worker/src/workers/mod.rs
- svc/pkg/cdn/worker/src/workers/mod.rs
- svc/pkg/cf-custom-hostname/worker/src/workers/mod.rs
- svc/pkg/cloud/worker/src/workers/mod.rs
- svc/pkg/external/worker/src/workers/mod.rs
- svc/pkg/game-user/worker/src/workers/mod.rs
- svc/pkg/job-log/worker/src/workers/mod.rs
- svc/pkg/job-run/worker/src/workers/mod.rs
- svc/pkg/kv/worker/src/workers/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_find/find.rs
- svc/pkg/mm/worker/src/workers/mod.rs
- svc/pkg/module/worker/src/workers/mod.rs
- svc/pkg/push-notification/worker/src/workers/mod.rs
- svc/pkg/team-dev/worker/src/workers/mod.rs
- svc/pkg/team-invite/worker/src/workers/mod.rs
- svc/pkg/team/worker/src/workers/mod.rs
- svc/pkg/upload/worker/src/workers/mod.rs
- svc/pkg/user-dev/worker/src/workers/mod.rs
- svc/pkg/user-follow/worker/src/workers/mod.rs
- svc/pkg/user-presence/worker/src/workers/mod.rs
- svc/pkg/user-report/worker/src/workers/mod.rs
- svc/pkg/user/worker/src/workers/mod.rs
Fixes RVT-3504
Script:
```python
import os
import re
def modify_rust_files(directory):
for root, _, files in os.walk(directory):
for file in files:
if file.endswith('.rs'):
file_path = os.path.join(root, file)
with open(file_path, 'r') as f:
content = f.read()
matches = re.findall(r'chirp_worker::workers!\[(.*?)\];', content, re.DOTALL)
if matches:
mods = '\n'.join([f'mod {name.strip()};' for name in matches[0].split(',') if name.strip()])
content = mods + '\n\n' + content
with open(file_path, 'w') as f:
f.write(content)
modify_rust_files('.')
```
> Reformat worker mod files

- CHANGELOG.md
- svc/pkg/mm/worker/src/workers/lobby_create/oci_config.rs
For 100% compatability with Docker, the rootfs needs to be writable.
> Fix runc rootfs not being read/write

- lib/global-error/src/macros.rs
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request adds new macros and updates existing ones in the `lib/global-error/src/macros.rs` file. The new macros include `location!`, `err_code!`, `bail!`, `retry_bail!`, `ensure!`, `ensure_eq!`, `unwrap_ref!`, `bail_with!`, `ensure_with!`, `ensure_eq_with!`, `unwrap_with_ref!`, and `unwrap_with!`. These macros provide convenient ways to handle errors and exit early with error messages and associated metadata.
> 
> ## What changed
> - Added `location!` macro to construct a `Location` object with file name, line number, and column number.
> - Added `err_code!` macro to construct an error with a specified error code, optional metadata, and context. …
> Add docs to existing macros

- lib/global-error/src/ext.rs
- lib/global-error/src/macros.rs
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request adds a new macro called `AssertionErrorUnwrap` and a new macro called `location` to the `macros` module of the `global-error` library. The code changes also include the addition of various error handling macros and examples of how to use them.
> 
> ## What changed
> - Added a new macro called `AssertionErrorUnwrap` to the `macros` module of the `global-error` library.
> - Added a new macro called `location` that constructs a `Location` object with the current file name, line number, and column number.
> - Added various error handling macros and examples of how to use them.
> 
> ## How to test
> - Compile and run the code with the new …
> Change unwrap!() to handle results

- CHANGELOG.md
- svc/pkg/mm/worker/src/workers/lobby_create/scripts/run.sh
Preivously, we used an instance of Vector for stdout and stderr
individually in order to determine the stream type. Now, we prefix each
stream with metadata and parse it inside of Vector in order to only run
one Vector instance.
Adding a sleep after the runc command lets Vector capture the logs. This
fixes applications not shipping logs if they exit immediately.
Fixes RVT-3509
> Ship logs with a single instance of Vector, fix not shipping logs on immediate exit

- CHANGELOG.md
- docs/infrastructure/API_TIMEOUTS.md
- infra/tf/k8s_infra/traefik.tf
- lib/util/macros/src/lib.rs
> Decrease select_with_timeout to fix 520 error

- CHANGELOG.md
- docs/infrastructure/API_TIMEOUTS.md
- errors/api/request-timeout.md
- lib/api-helper/macros/src/lib.rs
> Add request timeout to api-helper

- svc/pkg/job-run/worker/src/workers/cleanup.rs
- svc/pkg/job-run/worker/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/job-run/worker/src/workers/stop.rs
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/team-invite/worker/src/workers/consume.rs
Remaining transactions that were not migrated correctly from the SQL macro refactor
Fixes RVT-3520
> Fix missing uses of transactions

- lib/global-error/Cargo.toml
- lib/types/build/Cargo.toml
- lib/types/build/src/lib.rs
- lib/types/core/Cargo.toml
Allows compiling `global-error` without having protobuf installed on your host machine.
> Add protobuf-src flag to global-error & types

- lib/bolt/core/src/tasks/gen.rs
> Add BOLT_SKIP_GEN env var for faster commands

- lib/util/env/src/lib.rs
- proto/backend/billing.proto
> Upadate billing schema

- CHANGELOG.md
- infra/tf/infra_artifacts/README.md
- infra/tf/infra_artifacts/job_runner.tf
- infra/tf/infra_artifacts/main.tf
- infra/tf/infra_artifacts/providers.tf
- infra/tf/infra_artifacts/vars.tf
- lib/bolt/core/src/tasks/infra/mod.rs
- lib/job-runner/.dockerignore
- lib/job-runner/Dockerfile
- svc/pkg/infra/buckets/artifacts/Service.toml
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_create/nomad_job.rs
- svc/pkg/mm/worker/src/workers/lobby_create/scripts/setup.sh
- svc/pkg/mm/worker/src/workers/lobby_create/scripts/setup_job_runner.sh
Allows for creating and storing artifacts required in our infrastructure outside of Kubernetes.
We have a lot of complex logic running outside of the comfort of Kubernetes. We've been hacking this logic together with shell scripts and it's reached a breaking point. This allows us to write these components in Rust and ship them to S3 where they can be distributed to our infrastructure reliably.
> Add infra-artifcats bucket, upload job-runner to artifacts

- CHANGELOG.md
- infra/tf/dns/dns.tf
- infra/tf/k8s_cluster_aws/load_balancer_controller.tf
- infra/tf/k8s_infra/traefik.tf
- infra/tf/k8s_infra/traefik_tunnel.tf
- infra/tf/redis_aws/outputs.tf
ELB is problematic because the amount of requests we make to the cluter get sent to a surge queue which time out and fail to complete.
> Switch from AWS ELB to NLB to fix surge queue length

- svc/pkg/mm/worker/src/workers/lobby_create/scripts/setup_oci_bundle.sh
> Validate user cannot run as root

- CHANGELOG.md
- infra/tf/modules/write_secret/main.tf
- infra/tf/modules/write_secret/vars.tf
- lib/bolt/Cargo.lock
- lib/bolt/cli/Cargo.toml
- lib/bolt/cli/src/commands/secret.rs
- lib/bolt/core/src/tasks/config/generate.rs
- lib/bolt/core/src/tasks/config/mod.rs
> Add bolt secret set command

- CHANGELOG.md
- infra/tf/k8s_infra/loki.tf
> Make Loki resources configurable

- lib/job-runner/src/main.rs
> Log preview lines in job-runner

- lib/chirp/worker/src/manager.rs
> Add name to consumer Redis clients

- CHANGELOG.md
- lib/api-helper/build/src/macro_util.rs
> Remove excess logging in api-helper

- CHANGELOG.md
- lib/api-helper/build/src/start.rs
- lib/api-helper/macros/src/lib.rs
> Instrument & box api-helper futures

- scripts/forward/traefik.sh
- scripts/forward/traefik_tunnel.sh
> Update forward Treafik scripts

- CHANGELOG.md
- lib/pools/Cargo.toml
- lib/pools/src/lib.rs
- svc/Cargo.lock
> Upgrade async-nats

- CHANGELOG.md
- infra/default-builds/dockerfiles/test-mm-lobby-echo/Dockerfile
- infra/default-builds/dockerfiles/test-mm-lobby-echo/src/main.rs
- infra/default-builds/outputs/test-mm-lobby-echo-tag.txt
- infra/default-builds/outputs/test-mm-lobby-echo.tar
> Handle SIGTERM in test-mm-lobby-echo

- CHANGELOG.md
- svc/pkg/job-run/worker/src/workers/create/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_ready_set.rs
> Dynamically sleep for Treafik config update in mm-lobby-ready-set

- CHANGELOG.md
- infra/tf/k8s_infra/nomad.tf
- infra/tf/k8s_infra/traefik_tunnel.tf
- lib/bolt/core/src/dep/terraform/install_scripts/components.rs
- lib/bolt/core/src/dep/terraform/install_scripts/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
> Expose each Nomad server individually via tunnel

- rustfmt.toml
- scripts/cargo_fmt/fmt.sh
This makes some changes to `rustfmt.toml` that I think align with our ideas of how things should be formatted. Most importantly is `StdExternalCrate` ([link](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=import#StdExternalCrate%5C%3A)) for imports:
> Discard existing import groups, and create three groups for:
> std, core and alloc,
external crates,
self, super and crate imports.
```
use alloc::alloc::Layout;
use core::f32;
use std::sync::Arc;
use broker::database::PooledConnection;
use chrono::Utc;
use juniper::{FieldError, FieldResult};
use uuid::Uuid;
use super::schema::{Context, Payload};
use super::update::convert_publish_payload;
use crate::models::Event;
```
Change to `rustfmt.toml` (though it should be commented out, see below)
```
hard_tabs = true
imports_granularity …
```
> Import fmt changes

- CHANGELOG.md
- errors/claims/missing-entitlement.md
- errors/token/invalid.md
- lib/claims/src/lib.rs
- svc/api/cloud/src/auth.rs
- svc/api/cloud/src/route/auth.rs
- svc/api/cloud/src/route/devices/links.rs
- svc/api/cloud/src/route/games/avatars.rs
- svc/api/cloud/src/route/games/builds.rs
- svc/api/cloud/src/route/games/cdn.rs
- svc/api/cloud/src/route/games/matchmaker.rs
- svc/api/cloud/src/route/games/mod.rs
- svc/api/cloud/src/route/games/namespaces/analytics.rs
- svc/api/cloud/src/route/games/namespaces/logs.rs
- svc/api/cloud/src/route/games/namespaces/mod.rs
- svc/api/cloud/src/route/games/tokens.rs
- svc/api/cloud/src/route/games/versions.rs
- svc/api/group/src/auth.rs
- svc/api/identity/src/auth.rs
- svc/api/kv/src/auth.rs
- svc/api/matchmaker/src/auth.rs
**MERGE WITH** https://app.graphite.dev/github/pr/rivet-gg/rivet-ee/25/Allow-admin-access-to-cloud-endpoints
Fixes RVT-3604
Fixes RVT-3603
- Allow admin users to access all dashboard pages
- Improved errors for invalid tokens
> Allow admin access to cloud endpoints, add token errors

- .github/workflows/rust.yaml
The cargo-deny-action made a breaking change that caused our arugments flag to have a duplicate `--manifest-path` arg
> Fix cargo deny manifest path

- lib/bolt/cli/src/commands/ssh.rs
- lib/bolt/core/src/tasks/ssh.rs
> feat(bolt): add region filter to ssh command

- .devcontainer/devcontainer.json
- release-please-config.json
> chore: format

- lib/bolt/core/src/tasks/check.rs
> fix(bolt): clarify 1password service token warning

- CHANGELOG.md
- lib/bolt/core/src/dep/terraform/install_scripts/components.rs
> Reduce ATS cache size

- lib/bolt/config/src/ns.rs
- lib/bolt/core/src/context/project.rs
- lib/bolt/core/src/context/service.rs
- lib/job-runner/src/main.rs
- proto/backend/matchmaker.proto
- svc/Cargo.lock
- svc/Cargo.toml
- svc/pkg/faker/ops/game/Cargo.toml
- svc/pkg/faker/ops/game/src/lib.rs
- svc/pkg/game/ops/version-validate/Cargo.toml
- svc/pkg/game/ops/version-validate/src/lib.rs
- svc/pkg/mm-config/db/mm-config/migrations/20240228172257_toggle_root_host.up.sql
- svc/pkg/mm-config/ops/game-get/Cargo.toml
- svc/pkg/mm-config/ops/game-get/Service.toml
- svc/pkg/mm-config/ops/game-get/src/lib.rs
- svc/pkg/mm-config/ops/game-get/tests/integration.rs
- svc/pkg/mm-config/ops/game-upsert/Cargo.toml
- svc/pkg/mm-config/ops/game-upsert/Service.toml
- svc/pkg/mm-config/ops/game-upsert/src/lib.rs
- svc/pkg/mm-config/ops/game-upsert/tests/integration.rs
- svc/pkg/mm-config/types/game-get.proto
- svc/pkg/mm-config/types/game-upsert.proto
- svc/pkg/mm/worker/Cargo.toml
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_create/nomad_job.rs
fix(mm): attempting to run a root container will log to stderr
Fixes RVT-3523
Fixes MIS-144
> feat(mm): add config to opt-in individual games for host networking & root containers

- lib/job-runner/src/main.rs
- svc/pkg/mm/worker/src/workers/lobby_create/scripts/setup_oci_bundle.sh
> chore(job-runner): send explicit "Aborting" message to stderr if job-runner fails to setup container

- svc/api/cloud/src/auth.rs
- svc/api/group/src/auth.rs
- svc/api/group/src/route/groups.rs
> fix: inaccessible admin routes

- svc/api/matchmaker/src/route/lobbies.rs
> fix: only select primary hostname in mm endpoints

- svc/pkg/job/standalone/gc/src/lib.rs
> fix(job): gc was not stopping jobs which failed to stop on nomad

- infra/tf/k8s_infra/nomad.tf
- svc/pkg/mm/worker/src/workers/lobby_ready_set.rs
> Fix bad restack

- proto/backend/cluster.proto
- svc/pkg/cluster/db/cluster/migrations/20231201000927_init.up.sql
- svc/pkg/cluster/ops/datacenter-get/src/lib.rs
- svc/pkg/cluster/types/msg/datacenter-create.proto
- svc/pkg/cluster/worker/src/workers/datacenter_create.rs
> fix: restructure datacenter table

- svc/Cargo.lock
- svc/Cargo.toml
- svc/pkg/job/standalone/gc/Cargo.toml
- svc/pkg/job/standalone/gc/src/lib.rs
- svc/pkg/mm/ops/lobby-for-run-id/Cargo.toml
- svc/pkg/mm/ops/lobby-for-run-id/Service.toml
- svc/pkg/mm/ops/lobby-for-run-id/src/lib.rs
- svc/pkg/mm/ops/lobby-for-run-id/tests/integration.rs
- svc/pkg/mm/types/lobby-for-run-id.proto
> chore(job): gc orphaned jobs from mm

- lib/bolt/core/src/context/service.rs
- svc/Cargo.lock
- svc/pkg/cluster/worker/Service.toml
- svc/pkg/linode/ops/instance-type-get/Service.toml
- svc/pkg/linode/ops/server-destroy/Service.toml
- svc/pkg/linode/ops/server-provision/Service.toml
- svc/pkg/linode/standalone/gc/Service.toml
- svc/pkg/linode/worker/Service.toml
- svc/pkg/tier/ops/list/Service.toml
> fix: remove erronious dep on linode & cloudflare tokens

- lib/bolt/cli/src/commands/secret.rs
- lib/bolt/core/src/tasks/config/generate.rs
Most people test the OSS repo locally. By defaulting to the public IP, the Terraform cluster fails to finish booting because it can't be accessed.
We'll provide better docs on the config after our OSS refresh.
> chore: replace auto-generate public ip with 127.0.0.1

- shell.nix
> feat(nix): skip building bolt in nix with NIX_SKIP_BOLT

- .devcontainer/devcontainer.json
- docs/infrastructure/devcontainers/RUST_WORKAROUND.md
- infra/tf/k8s_cluster_k3d/main.tf
- infra/tf/k8s_cluster_k3d/vars.tf
- lib/bolt/core/src/context/project.rs
- lib/bolt/core/src/context/service.rs
- lib/bolt/core/src/dep/cargo/cli.rs
- lib/bolt/core/src/dep/k8s/gen.rs
- lib/bolt/core/src/dep/terraform/gen.rs
- lib/bolt/core/src/tasks/check.rs
- lib/bolt/core/src/tasks/test.rs
- lib/bolt/core/src/tasks/up.rs
> chore(dev): respect CARGO_TARGET_DIR in bolt  & use non-mounted target in dev container

- infra/tf/dns/cert_packs.tf
- svc/Cargo.lock
- svc/pkg/cluster/db/cluster/migrations/20231201000927_init.up.sql
- svc/pkg/cluster/standalone/gc/src/lib.rs
- svc/pkg/cluster/types/msg/server-install-complete.proto
- svc/pkg/cluster/types/msg/server-install.proto
- svc/pkg/cluster/util/src/lib.rs
- svc/pkg/cluster/worker/src/workers/nomad_node_drain_complete.rs
- svc/pkg/cluster/worker/src/workers/server_destroy.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
- svc/pkg/cluster/worker/src/workers/server_install_complete.rs
- svc/pkg/cluster/worker/src/workers/server_provision.rs
- svc/pkg/linode/ops/server-destroy/Cargo.toml
- svc/pkg/linode/ops/server-destroy/src/lib.rs
- svc/pkg/linode/ops/server-provision/Cargo.toml
- svc/pkg/linode/ops/server-provision/README.md
- svc/pkg/linode/ops/server-provision/src/lib.rs
- svc/pkg/linode/standalone/gc/src/lib.rs
- svc/pkg/linode/types/msg/prebake-install-complete.proto
- svc/pkg/linode/types/msg/prebake-provision.proto
- svc/pkg/linode/types/server-destroy.proto
- svc/pkg/linode/types/server-provision.proto
- svc/pkg/linode/util/src/lib.rs
- svc/pkg/linode/worker/Cargo.toml
- svc/pkg/linode/worker/src/workers/prebake_install_complete.rs
- svc/pkg/linode/worker/src/workers/prebake_provision.rs
- svc/pkg/linode/worker/tests/prebake_install_complete.rs
- svc/pkg/linode/worker/tests/prebake_provision.rs
> fix: expand prebake image variant system

- .gitignore
- lib/bolt/core/src/tasks/test.rs
- svc/pkg/cluster/util/build.rs
- svc/pkg/cluster/util/src/lib.rs
- svc/pkg/linode/ops/server-provision/src/lib.rs
- svc/pkg/linode/worker/src/workers/prebake_provision.rs
> fix: test isolation and install script hashing

- lib/claims/src/lib.rs
- proto/claims.proto
- svc/api/provision/src/auth.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
> fix: claims

- svc/pkg/cluster/util/src/lib.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
- svc/pkg/linode/standalone/gc/Cargo.toml
- svc/pkg/linode/standalone/gc/src/lib.rs
> fix: standardize token ttl

- svc/pkg/mm/util/src/key.rs
- svc/pkg/mm/worker/redis-scripts/lobby_find.lua
- svc/pkg/mm/worker/redis-scripts/nomad_node_closed_set.lua
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_find/find.rs
- svc/pkg/mm/worker/src/workers/nomad_node_closed_set.rs
> fix: remove /join regression

- lib/pools/src/utils/crdb.rs
- svc/pkg/cluster/worker/src/workers/server_drain.rs
- svc/pkg/cluster/worker/src/workers/server_undrain.rs
> fix: add transacitons

- .github/workflows/bolt-test.yaml
- lib/bolt/core/src/utils/db_conn.rs
> fix: encode query parameters in migrations

- svc/pkg/game/ops/namespace-get/tests/integration.rs
- svc/pkg/game/ops/version-validate/tests/integration.rs
- svc/pkg/ip/ops/info/Service.toml
- svc/pkg/ip/ops/info/src/lib.rs
- svc/pkg/job-run/worker/tests/stop.rs
> fix: game, ip, and job tests

- svc/pkg/team/ops/member-relationship-get/src/lib.rs
- svc/pkg/team/ops/member-relationship-get/tests/integration.rs
- svc/pkg/team/types/member-relationship-get.proto
> fix: team tests

- .github/workflows/bolt-test.yaml
- svc/api/traefik-provider/tests/basic.rs
- svc/pkg/user/ops/resolve-access-token/tests/integration.rs
> fix: route and access token tests

- lib/bolt/core/src/context/service.rs
- lib/bolt/core/src/dep/terraform/gen.rs
> fix: resolve minio url within k8s when using loopback cluster ip

- .vscode/settings.json
> chore(dev): move rust-anlayzer CARGO_TARGET_DIR to separate dir

- .github/workflows/bolt-test.yaml
- gen/secrets.baseline.json
- infra/nix/bolt/default.nix
- svc/pkg/build/ops/create/src/lib.rs
- svc/pkg/build/standalone/default-create/src/lib.rs
> fix: default build creation

- lib/bolt/config/src/ns.rs
- lib/bolt/core/src/tasks/test.rs
> feat: add toggle for load tests

- Taskfile.yaml
- docs/getting_started/DEVELOPMENT.md
- docs/infrastructure/dev-tunnel/SETUP.md
- infra/dev-tunnel/Taskfile.yaml
- infra/dev-tunnel/main.tf
- infra/dev-tunnel/providers.tf
- infra/dev-tunnel/server.tf
- infra/dev-tunnel/tls.tf
- infra/dev-tunnel/tunnel.tf
- infra/dev-tunnel/vars.tf
- shell.nix
> feat(infra): add ability to provision dev tunnel

- docs/packages/job/JOB_DRAINING_AND_KILL_TIMEOUTS.md
- svc/pkg/job-run/worker/src/workers/stop.rs
> chore: doc drain & kill timeouts

- scripts/fern/gen_inner.sh
> docs: Fern installation instructions for script

- svc/pkg/mm/worker/tests/lobby_find.rs
> fix: verify different tags give different lobby

- svc/Cargo.lock
- svc/Cargo.toml
- svc/pkg/cluster/ops/list/Cargo.toml
- svc/pkg/cluster/ops/list/Service.toml
- svc/pkg/cluster/ops/list/src/lib.rs
- svc/pkg/cluster/ops/list/tests/integration.rs
- svc/pkg/cluster/types/list.proto
> feat: add operation to list all clusters

- svc/Cargo.lock
- svc/pkg/cluster/worker/src/workers/server_destroy.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/rivet.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/files/rivet_create_hook.sh
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/mod.rs
> fix: require tunnel before rivet hook

- svc/pkg/cluster/worker/src/workers/datacenter_scale.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/files/rivet_create_hook.sh
- svc/pkg/cluster/worker/src/workers/server_provision.rs
> fix: server sql

- .devcontainer/Dockerfile
Since nix uses a newer version of glibc, this matches it more closely (so proc macros don't have trouble generating)
> chore: update devcontainer docker base image

- lib/bolt/core/src/tasks/test.rs
> fix: get tests working with new target

- svc/pkg/cluster/util/src/lib.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traffic_server.rs
> chore(cluster): increase storage reserved for system on ats

- infra/tf/k8s_infra/grafana_dashboards/rivet-logs.json
- svc/pkg/load-test/standalone/mm-sustain/src/lib.rs
> feat(grafana): rivet logs dashboard

- .devcontainer/devcontainer.json
This might cause some issues with existing files created with vscode (say when using the GUI Git to do certain things). But it's better that it's off root, since most of the time the host won't be root.
> chore: change devcontainer user off root

- docs/infrastructure/dev-tunnel/SETUP.md
> docs: add api scope to dev tunnel docs

- lib/api-helper/macros/src/lib.rs
- lib/api-helper/macros/src/utils.rs
> feat: add patch method to router

- svc/pkg/team/worker/src/workers/create.rs
- svc/pkg/team/worker/src/workers/join_request_create.rs
- svc/pkg/team/worker/src/workers/join_request_resolve.rs
- svc/pkg/team/worker/src/workers/member_create.rs
- svc/pkg/team/worker/src/workers/member_kick.rs
- svc/pkg/team/worker/src/workers/member_remove.rs
- svc/pkg/team/worker/src/workers/user_ban.rs
- svc/pkg/team/worker/src/workers/user_unban.rs
- svc/pkg/user-follow/ops/toggle/src/lib.rs
- svc/pkg/user-identity/ops/create/src/lib.rs
- svc/pkg/user/ops/avatar-upload-complete/src/lib.rs
- svc/pkg/user/worker/src/workers/create.rs
- svc/pkg/user/worker/src/workers/delete.rs
- svc/pkg/user/worker/src/workers/profile_set.rs
> chore: fix deprecated analytics events fields

- lib/api-helper/build/src/start.rs
- lib/util/core/src/timestamp.rs
- svc/pkg/load-test/standalone/sqlx/src/lib.rs
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/user-presence/worker/src/workers/leave.rs
> chore: remove unused code

- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/files/rivet_fetch_tls.sh
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/mod.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
> fix: tls install script not running on first boot

- svc/pkg/cluster/worker/src/workers/server_dns_create.rs
- svc/pkg/cluster/worker/src/workers/server_dns_delete.rs
> fix: leaked dns records

- svc/pkg/cluster/worker/src/workers/server_dns_create.rs
- svc/pkg/cluster/worker/src/workers/server_dns_delete.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
> fix: check for draining before installing/creating dns

- svc/pkg/cluster/worker/src/workers/datacenter_scale.rs
> fix: taint logic for job nodes with no nomad node

- infra/default-builds/dockerfiles/test-mm-lobby-echo/Dockerfile
- lib/bolt/core/src/dep/cargo/cli.rs
- lib/job-runner/Dockerfile
> chore(bolt): upgrade rust to 1.77.2

- .dockerignore
- lib/bolt/core/src/dep/cargo/cli.rs
cluster-util build.rs script relies on Git
This will be removed in a future PR
> fix(bolt): copy & install git in docker for cluster build.rs

- svc/api/status/src/route/matchmaker.rs
> fix(api-status): auto-delete lobby after testing connection

- scripts/fern/gen_inner.sh
> fix(fern): remove dupe fern gen from bad merge

- infra/default-builds/dockerfiles/test-mm-lobby-echo/Dockerfile
- infra/tf/cloudflare_tunnels/k8s.tf
- infra/tf/grafana/grafana.tf
- infra/tf/k8s_cluster_aws/overprovisioning.tf
- infra/tf/k8s_infra/clickhouse.tf
- infra/tf/k8s_infra/cockroachdb.tf
- infra/tf/k8s_infra/imagor.tf
- infra/tf/k8s_infra/loki.tf
- infra/tf/k8s_infra/minio.tf
- infra/tf/k8s_infra/nats.tf
- infra/tf/k8s_infra/nomad.tf
- infra/tf/k8s_infra/nsfw_api.tf
- infra/tf/k8s_infra/priority_class.tf
- infra/tf/k8s_infra/prometheus.tf
- infra/tf/k8s_infra/promtail.tf
- infra/tf/k8s_infra/redis.tf
- infra/tf/k8s_infra/traefik.tf
- infra/tf/k8s_infra/traefik_tunnel.tf
- infra/tf/k8s_infra/traffic_server.tf
- infra/tf/vector/vector.tf
- lib/bolt/core/src/dep/k8s/gen.rs
- lib/job-runner/Dockerfile
> chore(k8s): update priority classes to play nice with karpenter & preemption

- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
> fix(ats): don't send requests to ats nodes without install_complete_ts

- svc/pkg/job-run/worker/src/workers/nomad_monitor_eval_update.rs
- svc/pkg/job-run/worker/src/workers/stop.rs
> fix(job-run): fix leaking jobs with wrong param order

- infra/tf/k8s_infra/prometheus.tf
- infra/tf/k8s_infra/traffic_server.tf
Currently VPAs cause these issues:
- Autoscaling doesn't play nice with Karpenter
- Prometheus takes a long time to replay the WAL, which causes frequent Prometheus outages
- Prometheus is better managed manually, since the load varies dramatically
> chore(infra): disable vpa for prometheus & traffic server

- svc/pkg/cluster/worker/src/workers/server_dns_delete.rs
> fix: gracfully delete secondary dns record

- svc/pkg/job-run/worker/src/workers/stop.rs
> fix(job-run): correctly clean up leaked proxied ports

- infra/tf/k8s_cluster_aws/eks.tf
- infra/tf/k8s_cluster_aws/karpenter.tf
- infra/tf/k8s_cluster_aws/main.tf
> fix(infra): upgrade karpenter to 0.32 & disable compaction

- infra/tf/vector/vars.tf
- infra/tf/vector/vector.tf
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/vector.rs
> chore(vector): filter unneeded go & prom metrics

- svc/pkg/cluster/worker/src/workers/server_taint.rs
> fix(cluster): don't taint servers that have cloud_destroy_ts

- infra/tf/grafana/grafana_dashboards/cluster-provisioning.json
> fix(grafana): fix pool_type query on cluster nomad panels

- svc/pkg/job-run/worker/src/workers/nomad_monitor_alloc_plan.rs
> fix(job-run): don't write job proxied port if job already stopped

- svc/pkg/cluster/worker/src/workers/server_destroy.rs
- svc/pkg/cluster/worker/src/workers/server_dns_delete.rs
> fix(cluster): gg dns records leak if server destroyed before install complete

- lib/bolt/cli/src/commands/config.rs
- lib/bolt/config/src/ns.rs
- lib/bolt/core/src/context/project.rs
- lib/bolt/core/src/tasks/check.rs
> fix(bolt): dont fully parse config when pulling

- docs/getting_started/DEBUGGING.md
> docs: update debugging loki command

- lib/chirp-workflow/core/Cargo.toml
- lib/chirp-workflow/core/src/activity.rs
- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/operation.rs
- lib/chirp-workflow/core/src/prelude.rs
- lib/chirp-workflow/core/src/registry.rs
- lib/chirp-workflow/core/src/util.rs
- lib/chirp-workflow/core/src/workflow.rs
- lib/chirp-workflow/macros/src/lib.rs
- lib/global-error/src/error.rs
- svc/Cargo.lock
- svc/pkg/foo/worker/src/workflows/test.rs
> feat: global error raw variant

- lib/api-helper/build/src/ctx.rs
- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/mod.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/lib.rs
- lib/chirp-workflow/core/src/util.rs
- lib/chirp-workflow/core/src/worker.rs
- lib/operation/core/src/lib.rs
- svc/Cargo.lock
- svc/api/admin/Cargo.toml
> feat: add compat layer between old ctx and new workflows

- docs/libraries/workflow/ERRORS.md
- lib/chirp-workflow/core/src/activity.rs
- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/mod.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/operation.rs
- lib/chirp-workflow/core/src/prelude.rs
- lib/chirp-workflow/core/src/registry.rs
- lib/chirp-workflow/core/src/schema.rs
- lib/chirp-workflow/core/src/signal.rs
- lib/chirp-workflow/core/src/util.rs
- lib/chirp-workflow/core/src/workflow.rs
- lib/chirp-workflow/macros/src/lib.rs
- svc/pkg/workflow/db/workflow/migrations/20240430191643_init.up.sql
Fixes RVT-3763
Fixes RVT-3751
Fixes RVT-3749
> feat(workflows): add retries and timeouts

- svc/pkg/mm/ops/lobby-find-fail/src/lib.rs
- svc/pkg/mm/ops/lobby-find-lobby-query-list/src/lib.rs
- svc/pkg/mm/worker/src/workers/lobby_cleanup.rs
- svc/pkg/mm/worker/src/workers/lobby_stop.rs
> fix(mm): call mm-lobby-cleanup from mm-gc even for preemptive lobbies without sql row

- svc/pkg/mm/worker/src/workers/lobby_find/mod.rs
> fix(mm): correctly handle lobby not found error if joining direclty to lobby id that doesn't exist

- svc/pkg/game/ops/version-validate/src/lib.rs
This fixes both:
- accidental `rivet deploy` with unconfigured rivet.yaml (which submits an empty object)
- we don't handle unconfigured matchmaker correctly
> fix(mm): require specifying matchmaker config for new game versions

- lib/api-helper/build/Cargo.toml
- lib/api-helper/build/src/ctx.rs
- lib/api-helper/build/src/macro_util.rs
- lib/chirp-workflow/core/src/activity.rs
- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/api.rs
- lib/chirp-workflow/core/src/ctx/mod.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/mod.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/executable.rs
- lib/chirp-workflow/core/src/lib.rs
- lib/chirp-workflow/macros/src/lib.rs
- svc/Cargo.lock
- svc/pkg/foo/worker/src/workflows/test.rs
> feat(workflows): add api ctx for workflows

- proto/backend/job/log.proto
- svc/api/cloud/src/route/games/matchmaker.rs
- svc/pkg/job-log/ops/read/src/lib.rs
- svc/pkg/job-log/types/read.proto
> chore: make logs query consistent with nanoseconds

- svc/pkg/ip/ops/info/src/lib.rs
> fix(ip): cache ip queries

- svc/pkg/mm-config/ops/version-get/src/lib.rs
> chore: cache mm-config-version-get

- svc/pkg/mm/worker/src/workers/player_remove.rs
> fix(mm): clean up players from gc zset

- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/api.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/macros/src/lib.rs
> chore(workflows): clean up internals

- lib/pools/src/lib.rs
- lib/pools/src/utils/sql_query_macros.rs
- svc/pkg/cluster/standalone/default-update/src/lib.rs
> chore: increase sql conn acquire rate limits

- svc/pkg/mm-config/ops/version-get/src/lib.rs
> chore: handle game version configs with bad proto migrations

- lib/cache/build/src/getter_ctx.rs
- lib/cache/build/src/req_config.rs
- svc/pkg/mm-config/ops/version-get/src/lib.rs
> fix(cache): mixed values in Cache::fetch_all

- lib/chirp-workflow/core/src/ctx/workflow.rs
> chore(workflows): add workflow name to logs

- svc/Cargo.lock
- svc/pkg/cluster/util/Cargo.toml
- svc/pkg/cluster/util/build.rs
> chore(clusters): remove git as a dependency for cluster util

- infra/tf/vector/vector.tf
- lib/util/core/src/lib.rs
- lib/util/macros/src/lib.rs
- svc/api/cloud/src/route/games/matchmaker.rs
> fix(cloud): add clean timeout for matchmaker logs

- lib/chirp-workflow/core/src/worker.rs
> chore: increase workflow tick interval

- infra/tf/better_uptime/main.tf
- infra/tf/better_uptime/vars.tf
- infra/tf/grafana/grafana_dashboards/cluster-provisioning.json
- lib/bolt/core/src/dep/terraform/gen.rs
- svc/api/cloud/src/route/devices/links.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/mod.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/ok_server.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/traefik.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/files/ok_server.sh
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/mod.rs
- svc/pkg/cluster/worker/src/workers/server_install/mod.rs
> feat(clusters): gg monitor for better uptime

- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/mod.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/schema.rs
- svc/pkg/workflow/db/workflow/migrations/20240620200019_add_create_ts.up.sql
> fix(workflows): add ts dt

- infra/tf/k8s_infra/traefik_tunnel.tf
- infra/tf/tls/tunnel_server.tf
- svc/Cargo.lock
- svc/api/traefik-provider/Cargo.toml
- svc/api/traefik-provider/src/route/core.rs
- svc/api/traefik-provider/src/route/mod.rs
- svc/api/traefik-provider/src/route/tunnel.rs
- svc/api/traefik-provider/src/types.rs
> fix: add ip whitelist to tunnels

- .gitignore
- infra/misc/svc_scripts/install_ca.sh
- lib/bolt/core/src/dep/cargo/cli.rs
- lib/bolt/core/src/dep/k8s/gen.rs
- lib/bolt/core/src/tasks/test.rs
- lib/bolt/core/src/tasks/up.rs
> feat(bolt): run tests in containers

- svc/pkg/cluster/ops/datacenter-get/src/lib.rs
> fix(cluster): dc-get column mismatch

- svc/pkg/cluster/worker/src/workers/server_provision.rs
> fix(clusters): query vlan ips per datacenter

- infra/tf/infra_artifacts/job_runner.tf
- infra/tf/infra_artifacts/output.tf
- lib/bolt/core/src/context/service.rs
- lib/bolt/core/src/dep/terraform/output.rs
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
> chore: read job-runner from ats

- svc/pkg/mm/ops/lobby-runtime-aggregate/src/lib.rs
> fix(mm): move runtime aggregate logic into query

- lib/bolt/core/src/tasks/test.rs
> fix(bolt): exclude volumes when using native docker builder

- infra/tf/k8s_cluster_k3d/main.tf
- infra/tf/k8s_cluster_k3d/vars.tf
- lib/bolt/core/src/dep/terraform/gen.rs
> chore(k3d): disable volumes if using use_local_repo

- sdks/full/typescript/src/core/fetcher/Fetcher.ts
- sdks/runtime/typescript/src/core/fetcher/Fetcher.ts
Regarding #982 
Get rid of support for environments that don't provide `fetch`; this means the SDK will not install / import `node-fetch` or other fetch polyfills ourselves. 
Given the fact Node (along with most other) JS runtimes provide fetch api by default, this should have little to no impact (?). Users with abnormal js environments should probably have to install fetch by themselves and not through the rivet lib
> Get rid of require() call in sdks/typescript/ ... /Fetcher.ts

- infra/tf/k8s_infra/nomad.tf
- infra/tf/k8s_infra/vars.tf
- lib/bolt/core/src/context/project.rs
- lib/bolt/core/src/context/service.rs
- lib/bolt/core/src/dep/terraform/gen.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/components/nomad.rs
- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/mod.rs
> fix(infra): dynamically generate nomad server count in install script

- svc/pkg/cloud/worker/src/workers/version_name_reserve.rs
> chore(cloud): update default version format to not use special characters

- svc/pkg/cluster/worker/src/workers/server_install/install_scripts/files/traffic_server_configure.sh
> fix(clusters): fix trafficserver run dir permissions on reboot

- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/api.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/mod.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/prelude.rs
- lib/chirp-workflow/core/src/signal.rs
- lib/chirp-workflow/core/src/worker.rs
- lib/chirp-workflow/macros/src/lib.rs
- svc/pkg/foo/worker/src/workflows/test.rs
- svc/pkg/foo/worker/tests/test.rs
- svc/pkg/workflow/db/workflow/migrations/20240626202744_add_tags.up.sql
- Tags are a json blob attached to workflows
- Tags are optional
- When publishing a signal with tags, it will be consumed by any workflow with a superset of the signals own tags:
- a workflow with tags `{ "foo": 1, "bar": ["a"] }` will consume a signal with tags `{ "bar": ["a"] }`
- While any json is allowed, i assume CRDB JSON comparison queries perform better when its plain string comparison
> feat(workflows): add tags

- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/mod.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/event.rs
- lib/chirp-workflow/core/src/util.rs
- lib/chirp-workflow/core/src/worker.rs
- svc/pkg/workflow/db/workflow/migrations/20240711213725_signal_msg_events.up.sql
> feat(workflows): add message and signal history

- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/db/postgres.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/event.rs
> fix(workflows): add sql retries, improve history diverged errors

- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/util.rs
> fix(workflows): fix invalid event history graph

- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp/client/src/client.rs
- lib/chirp/worker/src/manager.rs
- lib/util/core/src/lib.rs
> feat(workflows): implement retry backoff for activity errors

- docs/libraries/workflow/GOTCHAS.md
- docs/libraries/workflow/LOOPS.md
- lib/bolt/Cargo.lock
- lib/chirp-workflow/core/src/ctx/backfill.rs
- lib/chirp-workflow/core/src/ctx/mod.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/signal.rs
- lib/chirp-workflow/macros/src/lib.rs
- lib/runtime/src/lib.rs
- svc/Cargo.lock
- svc/Cargo.toml
- svc/pkg/cluster/src/workflows/datacenter/mod.rs
- svc/pkg/cluster/src/workflows/datacenter/scale.rs
- svc/pkg/cluster/src/workflows/datacenter/tls_issue.rs
- svc/pkg/cluster/src/workflows/server/mod.rs
- svc/pkg/cluster/standalone/workflow-backfill/Cargo.toml
- svc/pkg/cluster/standalone/workflow-backfill/Service.toml
- svc/pkg/cluster/standalone/workflow-backfill/src/lib.rs
- svc/pkg/cluster/standalone/workflow-backfill/src/main.rs
- svc/pkg/linode/src/workflows/server/mod.rs
> feat(workflows, clusters): add workflow backfill service

- svc/Cargo.lock
- svc/pkg/cluster/Cargo.toml
- svc/pkg/cluster/src/util/mod.rs
- svc/pkg/cluster/src/workflows/datacenter/tls_issue.rs
- svc/pkg/cluster/src/workflows/server/dns_create.rs
- svc/pkg/cluster/src/workflows/server/dns_delete.rs
- svc/pkg/cluster/standalone/workflow-backfill/src/lib.rs
> fix: update cloudflare crate

- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/api.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/standalone.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/macros/src/lib.rs
- svc/pkg/cluster/src/ops/datacenter/get.rs
- svc/pkg/cluster/src/ops/datacenter/location_get.rs
- svc/pkg/cluster/src/workflows/datacenter/mod.rs
- svc/pkg/cluster/src/workflows/server/mod.rs
> fix: loops and cache

- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/registry.rs
- svc/pkg/cluster/src/lib.rs
- svc/pkg/cluster/src/workflows/datacenter/mod.rs
- svc/pkg/linode/src/lib.rs
> fix(workflows): Throw errors for duplicate workflows

- lib/chirp-workflow/core/src/ctx/backfill.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/registry.rs
- lib/chirp-workflow/core/src/util.rs
- svc/pkg/cluster/standalone/workflow-backfill/src/lib.rs
> fix(workflows): fix backfill

- docs/libraries/workflow/USEFUL_QUERIES.md
- lib/chirp-workflow/core/src/ctx/workflow.rs
- svc/pkg/cluster/standalone/datacenter-tls-renew/src/lib.rs
> fix(clusters): fix tls renew query

- svc/pkg/ds/ops/server-create/src/lib.rs
- svc/pkg/faker/ops/job-template/src/lib.rs
- svc/pkg/job-run/worker/src/workers/create/create_job.rs
- svc/pkg/mm-config/ops/version-prepare/src/prewarm_ats.rs
- svc/pkg/mm/worker/src/workers/lobby_create/nomad_job.rs
> fix(servers): remove migrate block

- svc/api/servers/Cargo.toml
- svc/api/servers/src/route/mod.rs
> fix: servers cors

- infra/default-builds/dockerfiles/test-ds-echo/Dockerfile
- infra/default-builds/dockerfiles/test-mm-lobby-echo/Dockerfile
- lib/bolt/core/src/dep/cargo/cli.rs
- lib/job-runner/Dockerfile
> chore(bolt): upgrade rust to 1.80.0

- svc/pkg/ds/worker/src/workers/nomad_monitor_alloc_plan.rs
> fix(servers): fix broken insert

- lib/chirp-workflow/core/src/db/pg_nats.rs
- svc/pkg/workflow/db/workflow/migrations/20240809230231_fix_loop_idx.up.sql
> fix(workflows): fix loops queries

- lib/chirp-workflow/core/src/signal.rs
- svc/pkg/cluster/src/workflows/cluster.rs
- svc/pkg/cluster/src/workflows/datacenter/mod.rs
- svc/pkg/cluster/src/workflows/server/mod.rs
- svc/pkg/linode/src/workflows/image.rs
- svc/pkg/linode/src/workflows/server/mod.rs
> fix(workflows): rename signals, improve failure handling for server install

- fern/definition/servers/common.yml
- lib/convert/src/impls/ds.rs
- proto/backend/ds.proto
- svc/api/traefik-provider/src/route/game_guard/dynamic_servers.rs
- svc/pkg/ds/db/servers/Service.toml
- svc/pkg/ds/db/servers/migrations/20240501133910_init.up.sql
- svc/pkg/ds/db/servers/migrations/20240809224504_add_idx.up.sql
- svc/pkg/ds/ops/server-create/Service.toml
- svc/pkg/ds/ops/server-create/src/lib.rs
- svc/pkg/ds/ops/server-delete/Service.toml
- svc/pkg/ds/ops/server-delete/src/lib.rs
- svc/pkg/ds/ops/server-get/src/lib.rs
- svc/pkg/ds/ops/server-list-for-env/src/lib.rs
- svc/pkg/ds/worker/src/workers/mod.rs
- svc/pkg/ds/worker/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/ds/worker/src/workers/nomad_monitor_alloc_update.rs
> chore: update start_ts to be set when networking is ready

- infra/tf/dns/cert_packs.tf
- infra/tf/dns/vars.tf
- infra/tf/tls/cloudflare.tf
- infra/tf/tls/vars.tf
- infra/tf/vector/vector.tf
- lib/bolt/config/src/ns.rs
- lib/bolt/core/src/context/project.rs
- lib/bolt/core/src/context/service.rs
- lib/bolt/core/src/dep/terraform/gen.rs
- lib/bolt/core/src/dep/terraform/output.rs
- lib/bolt/core/src/dep/terraform/remote_states.rs
- lib/bolt/core/src/tasks/infra/mod.rs
> chore: update opengb cf worker names

- errors/servers/servers_server_failed_to_create.md
- svc/api/servers/src/route/servers.rs
- svc/pkg/ds/src/workflows/server/mod.rs
- svc/pkg/linode/src/workflows/server/mod.rs
> feat(ds): add server create failed message

- svc/Cargo.lock
- svc/pkg/ds/Cargo.toml
- svc/pkg/ds/src/workflows/server/destroy.rs
- svc/pkg/ds/tests/server_create.rs
> fix(ds): add back allocation signal

- fern/definition/servers/common.yml
- lib/chirp-workflow/core/src/worker.rs
- sdks/full/go/servers/types.go
- sdks/full/openapi/openapi.yml
- sdks/full/openapi_compat/openapi.yml
- sdks/full/rust-cli/docs/ServersServer.md
- sdks/full/rust-cli/src/models/servers_server.rs
- sdks/full/rust/docs/ServersServer.md
- sdks/full/rust/src/models/servers_server.rs
- sdks/full/typescript/archive.tgz
- sdks/runtime/typescript/archive.tgz
- svc/api/servers/src/route/mod.rs
- svc/pkg/ds/src/ops/server/get.rs
- svc/pkg/ds/src/types.rs
> fix(ds): fix server list & nomad monitor alloc plan queries

- svc/api/servers/src/route/servers.rs
- svc/pkg/ds/src/ops/server/list_for_env.rs
- svc/pkg/ds/src/workflows/server/destroy.rs
> chore(ds): split up destroy wf + add progress msg

- infra/tf/vector/vector.tf
- lib/job-runner/src/lib.rs
- lib/job-runner/src/log_shipper.rs
- lib/job-runner/src/main.rs
- svc/pkg/ds/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/ds/src/workflows/server/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_create/mod.rs
- svc/pkg/mm/worker/src/workers/lobby_create/nomad_job.rs
> fix(ds): fix logs

- lib/bolt/config/src/ns.rs
- lib/chirp-workflow/core/src/error.rs
- svc/pkg/cluster/standalone/workflow-backfill/src/lib.rs
- svc/pkg/linode/src/workflows/server/mod.rs
> fix: backfill script, crdb usage type

- svc/pkg/ds/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/ds/src/workers/nomad_monitor_alloc_update.rs
> fix(ds): disable retries for nomad monitors

- lib/api-helper/macros/src/lib.rs
> fix(api): move cors verification to endpoint level

- fern/definition/admin/clusters/common.yml
- lib/bolt/cli/src/commands/cluster/datacenter.rs
- svc/pkg/cluster/src/workflows/server/drain.rs
- svc/pkg/cluster/src/workflows/server/mod.rs
> fix(clusters): add drain padding to nomad

- svc/pkg/cluster/src/workflows/server/drain.rs
- svc/pkg/cluster/src/workflows/server/mod.rs
- svc/pkg/ds/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/ds/src/workers/nomad_monitor_alloc_update.rs
- svc/pkg/ds/src/workers/nomad_monitor_eval_update.rs
> fix(clusters): remove nomad drain complete signal

- svc/pkg/ds/src/workers/nomad_monitor_eval_update.rs
- svc/pkg/job-run/src/util.rs
- svc/pkg/job-run/src/workers/nomad_monitor_alloc_plan.rs
- svc/pkg/job-run/src/workers/nomad_monitor_alloc_update.rs
- svc/pkg/job-run/src/workflows/drain_all.rs
Fixes RVTEE-575
**Not manually tested**
> fix(job-run): delete second allocation immediately

- fern/definition/servers/builds.yml
- fern/definition/servers/datacenters.yml
- fern/definition/servers/logs.yml
> fix: update api endpoint names

- lib/chirp-workflow/core/src/builder/common/message.rs
- lib/chirp-workflow/core/src/builder/common/mod.rs
- lib/chirp-workflow/core/src/builder/common/signal.rs
- lib/chirp-workflow/core/src/builder/common/workflow.rs
- lib/chirp-workflow/core/src/builder/mod.rs
- lib/chirp-workflow/core/src/builder/workflow/message.rs
- lib/chirp-workflow/core/src/builder/workflow/mod.rs
- lib/chirp-workflow/core/src/builder/workflow/signal.rs
- lib/chirp-workflow/core/src/builder/workflow/sub_workflow.rs
- lib/chirp-workflow/core/src/compat.rs
- lib/chirp-workflow/core/src/ctx/activity.rs
- lib/chirp-workflow/core/src/ctx/api.rs
- lib/chirp-workflow/core/src/ctx/common.rs
- lib/chirp-workflow/core/src/ctx/listen.rs
- lib/chirp-workflow/core/src/ctx/mod.rs
- lib/chirp-workflow/core/src/ctx/operation.rs
- lib/chirp-workflow/core/src/ctx/standalone.rs
- lib/chirp-workflow/core/src/ctx/test.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/error.rs
- lib/chirp-workflow/core/src/lib.rs
- lib/chirp-workflow/core/src/registry.rs
> chore(workflows): clean up internal contexts

- infra/tf/grafana/grafana_dashboards/chirp-workflow.json
- lib/chirp-workflow/core/src/ctx/common.rs
- lib/chirp-workflow/core/src/ctx/workflow.rs
- lib/chirp-workflow/core/src/error.rs
- lib/util/core/src/lib.rs
- svc/pkg/cluster/src/ops/server/lost_list.rs
- svc/pkg/cluster/src/ops/server/prune_with_filter.rs
- svc/pkg/cluster/src/workflows/server/drain.rs
- svc/pkg/ds/src/workers/drain_all.rs
- svc/pkg/ds/src/workflows/server/mod.rs
- svc/pkg/job-run/src/workers/drain_all.rs
- svc/pkg/nomad/standalone/monitor/src/monitors/alloc_plan.rs
- svc/pkg/nomad/standalone/monitor/src/monitors/alloc_update.rs
- svc/pkg/nomad/standalone/monitor/src/monitors/eval_update.rs
> fix(workflows): implement backoff for timeouts

- docs/libraries/workflow/DEVELOPING.md
- infra/tf/grafana/grafana_dashboards/chirp-workflow.json
- lib/bolt/cli/src/commands/cluster/server.rs
- lib/chirp-workflow/core/src/builder/workflow/signal.rs
- svc/pkg/cluster/src/workflows/server/install/mod.rs
> fix: fix signal history divergence
